#!/usr/bin/env python3

import hammer_vlsi
from hammer_vlsi import CLIDriver, HammerToolHookAction

from typing import Dict, Callable, Optional, List

def example_place_tap_cells(x: hammer_vlsi.HammerTool) -> bool:
    x.append('''
# TODO
''')
    return True

def intech22_pre_place_opt(x: hammer_vlsi.HammerTool) -> bool:
    # TODO: Figure out common_ui replacement for this
    x.verbose_append("eval_legacy {setPlaceMode -place_global_ignore_scan false}")
    return True

class ExampleDriver(CLIDriver):
    def get_extra_par_hooks(self) -> List[HammerToolHookAction]:
        return [hammer_vlsi.HammerTool.make_replacement_hook("place_tap_cells", example_place_tap_cells),
                hammer_vlsi.HammerTool.make_pre_insertion_hook("place_opt_design", intech22_pre_place_opt)]

if __name__ == '__main__':
    ExampleDriver().main()
